In [1]:
import numpy as np

In [2]:
#Vectorization

In [3]:
arr = np.zeros((2,10))

In [4]:
arr+10 #10 is scalar

array([[10., 10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10., 10.]])

In [5]:
arr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [6]:
arr2 = np.ones((2,10))

In [7]:
arr2

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [8]:
arr+arr2 #Both operands are arrays

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [9]:
l1 = [1,2,4,5]
l2 = [3,4,6,7]

In [10]:
#Adding two list
sum = []
for i,_ in enumerate(l1): #0,1 1,2 2,4 3,5
    sum.append(l1[i] + l2[i])
print(sum)

[4, 6, 10, 12]


In [11]:
#where

In [12]:
marks = np.array([75,39,50, 80,90])

In [13]:
x = np.where(marks>=50,"Pass", "Fail")

In [14]:
x

array(['Pass', 'Fail', 'Pass', 'Pass', 'Pass'], dtype='<U4')

In [15]:
salary = np.array([10,70, 80, 50, 30])

In [16]:
incremented_salary = np.where(salary<50, salary*1.1, salary*1.05)

In [17]:
incremented_salary.dtype

dtype('float64')

In [18]:
arr = np.arange(1,101).reshape((10,10))

In [19]:
arr

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [20]:
arr.T

array([[  1,  11,  21,  31,  41,  51,  61,  71,  81,  91],
       [  2,  12,  22,  32,  42,  52,  62,  72,  82,  92],
       [  3,  13,  23,  33,  43,  53,  63,  73,  83,  93],
       [  4,  14,  24,  34,  44,  54,  64,  74,  84,  94],
       [  5,  15,  25,  35,  45,  55,  65,  75,  85,  95],
       [  6,  16,  26,  36,  46,  56,  66,  76,  86,  96],
       [  7,  17,  27,  37,  47,  57,  67,  77,  87,  97],
       [  8,  18,  28,  38,  48,  58,  68,  78,  88,  98],
       [  9,  19,  29,  39,  49,  59,  69,  79,  89,  99],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]])

In [21]:
arr

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [22]:
arr.transpose()

array([[  1,  11,  21,  31,  41,  51,  61,  71,  81,  91],
       [  2,  12,  22,  32,  42,  52,  62,  72,  82,  92],
       [  3,  13,  23,  33,  43,  53,  63,  73,  83,  93],
       [  4,  14,  24,  34,  44,  54,  64,  74,  84,  94],
       [  5,  15,  25,  35,  45,  55,  65,  75,  85,  95],
       [  6,  16,  26,  36,  46,  56,  66,  76,  86,  96],
       [  7,  17,  27,  37,  47,  57,  67,  77,  87,  97],
       [  8,  18,  28,  38,  48,  58,  68,  78,  88,  98],
       [  9,  19,  29,  39,  49,  59,  69,  79,  89,  99],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]])

In [23]:
arr = np.array([1,3,4,5,2])

In [24]:
arr.mean()

3.0

In [25]:
arr.cumsum()

array([ 1,  4,  8, 13, 15], dtype=int32)

In [26]:
arr.cumprod()

array([  1,   3,  12,  60, 120], dtype=int32)

In [27]:
#Procedure Vs. Function
#Procedure doesn't return any value
#Function returns a value

In [28]:
#Methods for boolean arrays

In [29]:
gender = np.array(['Male', 'Female', 'Male', 'Male', 'Male'])

In [30]:
arr = gender == 'Male'
arr

array([ True, False,  True,  True,  True])

In [31]:
arr.sum()

4

In [32]:
arr = gender == 'Female'
arr.sum()

1

In [33]:
arr

array([False,  True, False, False, False])

In [34]:
arr.any()

True

In [35]:
arr.all()

False

In [36]:
arr = np.array([2,4,10,20,16])

In [37]:
x = (arr%2 == 0)

In [38]:
x

array([ True,  True,  True,  True,  True])

In [39]:
x.all()

True

In [40]:
#Universal quantifier
#Existential quantifier

In [41]:
arr

array([ 2,  4, 10, 20, 16])

In [42]:
arr.sort()

In [43]:
arr

array([ 2,  4, 10, 16, 20])

In [44]:
arr.sort() #Inplace

In [45]:
arr[::-1]

array([20, 16, 10,  4,  2])

In [46]:
arr = np.array([1,2,4,1,6,2])

In [47]:
u = np.unique(arr)

In [48]:
#Save array

In [49]:
np.save('data',u)

In [50]:
#Load array

In [51]:
content = np.load('data.npy')d

In [52]:
content

array([1, 2, 4, 6])

In [53]:
#Saving multiple arrays

In [54]:
students = np.array(["Ali","Asad","Ahmed"])
marks = np.array([30,20,60])

In [55]:
np.savez('arrays',std=students,m=marks)

In [56]:
results = np.load('arrays.npz')

In [57]:
results['std']

array(['Ali', 'Asad', 'Ahmed'], dtype='<U5')

In [58]:
results['m']

array([30, 20, 60])

In [59]:
arr=np.arange(16).reshape((4,4))

In [60]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [61]:
arr.diagonal()

array([ 0,  5, 10, 15])

In [62]:
arr.trace()

30

In [63]:
arr1=np.arange(10,26).reshape((4,4))

In [64]:
arr.dot(arr1)

array([[ 116,  122,  128,  134],
       [ 372,  394,  416,  438],
       [ 628,  666,  704,  742],
       [ 884,  938,  992, 1046]])

In [65]:
from numpy import linalg

In [66]:
linalg.det(arr)

-2.9582283945787796e-30

In [67]:
linalg.eig(arr)

(array([ 3.24642492e+01, -2.46424920e+00,  4.52933966e-17, -1.52275132e-15]),
 array([[-0.11417645, -0.7327781 ,  0.01936986, -0.48846795],
        [-0.3300046 , -0.28974835,  0.38216644,  0.83598112],
        [-0.54583275,  0.15328139, -0.82244247, -0.20655839],
        [-0.76166089,  0.59631113,  0.42090617, -0.14095478]]))

In [68]:
linalg.inv(np.array([[1,5],[9,8]]))

array([[-0.21621622,  0.13513514],
       [ 0.24324324, -0.02702703]])

In [69]:
linalg.qr(arr)

(array([[ 0.        , -0.83666003,  0.48308786,  0.25812035],
        [-0.26726124, -0.47809144, -0.8365087 ,  0.01591196],
        [-0.53452248, -0.11952286,  0.22375381, -0.80618499],
        [-0.80178373,  0.23904572,  0.12966702,  0.53215267]]),
 array([[-1.49666295e+01, -1.65701970e+01, -1.81737645e+01,
         -1.97773319e+01],
        [ 0.00000000e+00, -1.19522861e+00, -2.39045722e+00,
         -3.58568583e+00],
        [ 0.00000000e+00,  0.00000000e+00, -1.71941189e-15,
         -5.12511879e-15],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         -8.82043219e-16]]))

In [70]:
linalg.svd(arr)

(array([[-0.09184212, -0.83160389,  0.52939495,  0.14050262],
        [-0.31812733, -0.44586433, -0.8105844 ,  0.20725087],
        [-0.54441254, -0.06012478,  0.03298396, -0.8360096 ],
        [-0.77069775,  0.32561478,  0.2482055 ,  0.48825611]]),
 array([3.51399637e+01, 2.27661021e+00, 8.80118491e-16, 4.41188001e-17]),
 array([[-0.42334086, -0.47243254, -0.52152422, -0.57061589],
        [ 0.72165263,  0.27714165, -0.16736932, -0.6118803 ],
        [ 0.5427818 , -0.66899815, -0.29034911,  0.41656546],
        [ 0.0734024 , -0.50243554,  0.78466387, -0.35563073]]))

In [71]:
np.random.normal(3,4,(3,3))

array([[ 3.71492879,  6.68100023, -2.88994293],
       [10.54011541,  5.02958504,  2.81186051],
       [ 3.36937634,  5.76603521,  2.92763874]])

In [72]:
np.random.gamma(1,2,(4,4))

array([[0.69998257, 0.93381039, 0.59680928, 0.10902411],
       [4.55012288, 1.24187778, 1.31943742, 3.87081677],
       [0.25689425, 2.76860654, 0.89503158, 2.47209397],
       [2.65602637, 2.47777075, 0.15610742, 1.86123782]])

In [73]:
np.random.seed(5)

In [74]:
np.random.rand()

0.22199317108973948

In [75]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [76]:
arr.reshape((2,2,4))

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [77]:
arr = np.arange(16)

In [78]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [79]:
arr.reshape((4,4),order='F') #column major order

array([[ 0,  4,  8, 12],
       [ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15]])

In [80]:
arr.reshape((4,4),order='C') #row major order

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [81]:
arr = np.array([[1,8,7],[3,4,5],[9,0,1]])

In [82]:
arr

array([[1, 8, 7],
       [3, 4, 5],
       [9, 0, 1]])

In [83]:
arr.flatten()

array([1, 8, 7, 3, 4, 5, 9, 0, 1])

In [84]:
arr.ravel()

array([1, 8, 7, 3, 4, 5, 9, 0, 1])

In [85]:
arr.reshape(9)

array([1, 8, 7, 3, 4, 5, 9, 0, 1])

In [86]:
#Assignment: Difference between ravel and flatten

In [87]:
#Concatenate

In [88]:
a = np.array([[1,2],[3,4]])
b = np.array([[7,8],[9,10]])

In [89]:
print('a=',a)
print('b=',b)

a= [[1 2]
 [3 4]]
b= [[ 7  8]
 [ 9 10]]


In [90]:
np.concatenate((a,b),axis=0)

array([[ 1,  2],
       [ 3,  4],
       [ 7,  8],
       [ 9, 10]])

In [91]:
np.concatenate((a,b),axis=1)

array([[ 1,  2,  7,  8],
       [ 3,  4,  9, 10]])

In [92]:
a = np.array([[1,7,9],[2,3,4],[5,6,7]])
b = np.array([[9,4,9],[2,3,2],[0,6,7]])

In [93]:
np.concatenate((a,b))

array([[1, 7, 9],
       [2, 3, 4],
       [5, 6, 7],
       [9, 4, 9],
       [2, 3, 2],
       [0, 6, 7]])

In [94]:
np.hstack((a,b)) #concatenate axis = 1

array([[1, 7, 9, 9, 4, 9],
       [2, 3, 4, 2, 3, 2],
       [5, 6, 7, 0, 6, 7]])

In [95]:
np.vstack((a,b)) #concatenate axis = 0

array([[1, 7, 9],
       [2, 3, 4],
       [5, 6, 7],
       [9, 4, 9],
       [2, 3, 2],
       [0, 6, 7]])

In [96]:
np.r_[a,b] #concatenate axis = 0

array([[1, 7, 9],
       [2, 3, 4],
       [5, 6, 7],
       [9, 4, 9],
       [2, 3, 2],
       [0, 6, 7]])

In [107]:
np.c_[a,b] #concatenate axis = 1

array([[1, 7, 9, 9, 4, 9],
       [2, 3, 4, 2, 3, 2],
       [5, 6, 7, 0, 6, 7]])

In [108]:
x = np.array([1,9,9,7,1,2,3])

In [109]:
np.split(x,[3, 5])

[array([1, 9, 9]), array([7, 1]), array([2, 3])]

In [110]:
l = np.arange(2,7,2)

In [101]:
l

array([2, 4, 6])

In [102]:
x

array([1, 9, 9, 7, 1, 2, 3])

In [103]:
np.split(x,l)

[array([1, 9]), array([9, 7]), array([1, 2]), array([3])]

In [104]:
x = np.array([[1,3],[2,4]])

In [105]:
x

array([[1, 3],
       [2, 4]])

In [106]:
np.split(x,[1])

[array([[1, 3]]), array([[2, 4]])]