# Numpy


## Arrays

* Faster
* Contigous Memory Allocation
* Same Data Type
* If you want to increase size,recreate array

## List
  
* Slow
* Sparse Memory
* Differential Data types
* Can dynamically grow

### Numpy VS  List in Python

In [4]:
import numpy as np

In [5]:
python_list=range(1000000)  #A list from 0 to 1000000

In [6]:
numpy_array=np.arange(1000000) # An array from 0 to 1000000

### multiply a list with 5,  1000 times using list comprehension

In [7]:
%time for i in range(100): result=numpy_array* 5

CPU times: total: 172 ms
Wall time: 190 ms


### multiply numpy array with 5, 1000 times

In [8]:
%time for i in range(100): result = numpy_array * 5

CPU times: total: 203 ms
Wall time: 195 ms


### Numpy array creation methods

In [9]:
one_d_array=np.zeros(10)
one_d_array 

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
one_d_array = np.ones((10))
one_d_array

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [11]:
one_d_array*2

array([2., 2., 2., 2., 2., 2., 2., 2., 2., 2.])

In [12]:
#Creating array of any number
x=np.zeros(10)
x=x+5
x

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [13]:
x=np.arange(1,11)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
# Shape of array
x=np.zeros((3,2,5))
x 

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [15]:
x.shape

(3, 2, 5)

### Array of custom elements

In [16]:
x=np.array([1,3,7,9,10,16,78,18])
x

array([ 1,  3,  7,  9, 10, 16, 78, 18])

In [17]:
x.shape

(8,)

In [18]:
y=x.reshape((2,4))
y

array([[ 1,  3,  7,  9],
       [10, 16, 78, 18]])

In [19]:
y.shape

(2, 4)

In [20]:
y.ndim

2

In [21]:
y

array([[ 1,  3,  7,  9],
       [10, 16, 78, 18]])

# Accessing individual elements of array

In [22]:
y[0,3] #accessing only by specifying columns

9

In [23]:
y[1,2] #accessing by specifying (row,column)

78

In [24]:
z = y.reshape((2,2,2))

In [25]:
z

array([[[ 1,  3],
        [ 7,  9]],

       [[10, 16],
        [78, 18]]])

In [26]:
z[0,1,1]

9

In [27]:
z.ndim

3

In [28]:
z.dtype

dtype('int32')

# Slicing

In [29]:
y

array([[ 1,  3,  7,  9],
       [10, 16, 78, 18]])

In [30]:
#Slicing :Start,end, step
y=y.reshape(4,2)   #(row,column)

In [31]:
y

array([[ 1,  3],
       [ 7,  9],
       [10, 16],
       [78, 18]])

In [32]:
y[0:3]

array([[ 1,  3],
       [ 7,  9],
       [10, 16]])

In [33]:
y

array([[ 1,  3],
       [ 7,  9],
       [10, 16],
       [78, 18]])

In [34]:
y[0:3,1]

array([ 3,  9, 16])

In [35]:
y

array([[ 1,  3],
       [ 7,  9],
       [10, 16],
       [78, 18]])

In [36]:
y[::2]

array([[ 1,  3],
       [10, 16]])

In [37]:
y

array([[ 1,  3],
       [ 7,  9],
       [10, 16],
       [78, 18]])

In [38]:
y[::,0]

array([ 1,  7, 10, 78])

In [39]:
x

array([ 1,  3,  7,  9, 10, 16, 78, 18])

# Fancy Indexing


In [40]:
x[[3,5]]

array([ 9, 16])

In [41]:
x[[6,2]]

array([78,  7])

# Vectorized Operations

In [42]:
x = np.array([1,5,7])
y = np.array([3,2,9])

In [43]:
x+y

array([ 4,  7, 16])

In [44]:
x-y

array([-2,  3, -2])

In [45]:
x*y

array([ 3, 10, 63])

In [46]:
x/y

array([0.33333333, 2.5       , 0.77777778])

In [47]:
x//y


array([0, 2, 0], dtype=int32)

In [48]:
x*y**2

array([  9,  20, 567])

# Shapes

# 00000
## 11111
## 11111
## 11111
## 00000

In [49]:
arr=np.ones((10,10))

In [50]:
arr

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [51]:
arr[0]=0
arr[-1]=0

In [52]:
arr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

## 00000
## 10001
## 10001
## 10001
## 00000

In [53]:
arr=np.zeros((5,5))

In [54]:
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [55]:
arr[1:-1]=1

In [56]:
arr

array([[0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0.]])

In [57]:
x=np.array([1,8,9,10,11])
            #0123456  from left
            #-6-5-4-3-2-1  from right

In [58]:
x[-1]

11

In [59]:
x[-2]

10

In [60]:
x[-3]

9

# Assignment
##  1. Checkboard Pattern
  

# 01010
# 10101
# 01010
# 10101
# 01010

In [61]:
arr=np.zeros((5,5))

In [62]:
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [63]:
arr[1::2, ::2] = 1
arr[::2, 1::2] = 1            

In [64]:
arr

array([[0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0.]])

## 2. Football ground
#### 00000
#### 11111
#### 00000
#### 11111
#### 00000
#### 11111

In [65]:
arr=np.zeros((5,5))

In [66]:
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

# 3. Cross pattern

### 01110
### 10101
### 11011
### 10101
### 01110

In [67]:
np.empty((4,4))  #Random / Arbitary values

array([[4.67296746e-307, 1.69121096e-306, 1.51318196e-306,
        3.00390403e-307],
       [1.11261027e-306, 1.11256817e-306, 1.06811422e-306,
        1.42417221e-306],
       [1.11260619e-306, 8.90094053e-307, 1.86919378e-306,
        1.06809792e-306],
       [1.37962456e-306, 1.69111861e-306, 1.78020169e-306,
        7.56605918e-307]])

In [68]:
x

array([ 1,  8,  9, 10, 11])

In [69]:
x.dtype

dtype('int32')

# Comparison Between Matrices

In [70]:
salary=np.array([10,25,5,2])

In [71]:
salary[salary > 5]

array([10, 25])

# Numpy element-wise functions

In [72]:
nums= [10,20,56,78,90]

In [74]:
np.sin(nums)

array([-0.54402111,  0.91294525, -0.521551  ,  0.51397846,  0.89399666])

In [75]:
np.sqrt(nums)

array([3.16227766, 4.47213595, 7.48331477, 8.83176087, 9.48683298])

# Assignment
* try all functions

In [77]:
np.ceil(nums)

array([10., 20., 56., 78., 90.])

In [78]:
np.sign(nums)

array([1, 1, 1, 1, 1])

In [79]:
np.exp(nums)

array([2.20264658e+04, 4.85165195e+08, 2.09165950e+24, 7.49841700e+33,
       1.22040329e+39])

In [80]:
np.rint(nums)

array([10., 20., 56., 78., 90.])

In [81]:
np.modf(nums)

(array([0., 0., 0., 0., 0.]), array([10., 20., 56., 78., 90.]))

In [82]:
np.abs(nums)

array([10, 20, 56, 78, 90])

In [83]:
np.fabs(nums)

array([10., 20., 56., 78., 90.])

In [84]:
np.isnan(nums)

array([False, False, False, False, False])

In [85]:
np.isfinite(nums)

array([ True,  True,  True,  True,  True])

In [86]:
np.isinf(nums)

array([False, False, False, False, False])

In [87]:
np.cos(nums)

array([-0.83907153,  0.40808206,  0.85322011, -0.85780309, -0.44807362])

In [88]:
np.cosh(nums)

array([1.10132329e+04, 2.42582598e+08, 1.04582975e+24, 3.74920850e+33,
       6.10201647e+38])

In [89]:
np.log(nums)

array([2.30258509, 2.99573227, 4.02535169, 4.35670883, 4.49980967])

In [90]:
np.log2(nums)

array([3.32192809, 4.32192809, 5.80735492, 6.28540222, 6.4918531 ])

In [91]:
np.log1p(nums)

array([2.39789527, 3.04452244, 4.04305127, 4.36944785, 4.51085951])